[build]
target = "aarch64-apple-darwin"

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "target-feature=+fp16,+neon",
]

[target.aarch64-apple-ios]
rustflags = [
    "-C",
    "target-feature=+fp16,+neon",
]

[target.aarch64-apple-ios-sim]
rustflags = [
    "-C",
    "target-feature=+fp16,+neon",
]

[target.aarch64-linux-android]
rustflags = [
    "-C",
    "target-feature=+fp16,+neon",
]

[target.arm-linux-android]
rustflags = [
    "-C",
    "target-feature=+fp16,+neon",
]

[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=+simd128",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "target-feature=-avx,-avx2",
]
